Ruffification
DemocracyClub/WhoCanIVoteFor pull request #1664
Opened 2023-07-25 09:54 UTC by Bekabyx

I copied over the config from Sym's implementation on the website project, and added some additional rules so our auto-generated migrations and our config files don't trigger anything.

Todo: 
- Make remaining files compliant
- Update dev handbook with implementation/running instructions.
- Update documentation with running instructions.

```[tasklist]
### PR Checklist
- [ ] References a specific issue or if not, describes the bug or feature in detail
- [ ] Note what card in Trello this work relates to
- [ ] Instructions for how reviewers can test the code locally
- [ ] Tests have been added and/or updated
- [ ] Screenshot of the feature/bug fix (if applicable)
- [ ] If any new text is added, it's internationalized
- [ ] Any new elements have aria labels
- [ ] No unintentional console.logs left behind after debugging
- [ ] Did I use the clear and concise names for variables and functions?
- [ ] Did I explain all possible solutions and why I chose the one I did?
- [ ] Added any comments to make new functions clearer
- [ ] Did I added or updated any new dependencies? Explain why.
- [ ] Did I update the package.json and/or Pipfile.lock version if relevant?
- [ ] Have I rebased with the latest version of master?
- [ ] Added PR labels
- [ ] Update any history/changelog file
- [ ] Update any documentation
- [ ] Update dev handbook
```

2023-07-31 09:34 UTC, Bekabyx commented
Because this PR is massive here's a lis of files with handrolled changes:
- .circleci/config.yml
- INSTALL.md
- pyproject.toml
- requirements/testing.txt
- wcivf/apps/elections/import_helpers.py
- wcivf/apps/elections/models.py
- wcivf/apps/hustings/management/commands/import_hustings.py
- wcivf/apps/people/management/commands/import_companies.py
- wcivf/apps/profiles/management/commands/import_pcc_2016_profiles.py
- wcivf/settings/base.py
- wcivf/utils.py

This includes the work we discussed about context managers as well as restructuring of nested if statements which ruff doesn't like, plus a few other minor pieces like the new packages being installed and configured and the circleci job.

2023-07-31 11:38 UTC, symroe requested changes

2023-07-31 14:13 UTC, Bekabyx commented on pyproject.toml
> +    "--ignore=democracy_club/settings/local.py",
Fixed in most recent push 😎

2023-08-01 08:26 UTC, symroe approved these changes

2023-08-01 08:36 UTC, merged